version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: conf.py

formats:
  - pdf
  - epub
  
# Explicitly set the version of Python and its requirements
python:
  version: 3.7
  install:
    - requirements: requirements.txt
